id: I9CA7B9CC
ocr_import_info:
  timestamp: '2023-09-28T04:49:42.933278+00:00'
  batch_id: batch-e382
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-28 06:02:13.407966+00:00
last_modified: 2023-09-28 06:02:13.407974+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W29102
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW29102
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མངོན་པ་མཛོད་ཀྱི་ཉེར་མཁོ་དཀའ་གནས་གསལ་བྱེད་འགའ
  languages:
  - bo
  author: འཛམ་ཐང་མཁན་པོ་ཚོགས་གཉིས་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.8636745204468247
  ocr_word_median_confidence_index: 0.9005838
bases:
  I5114:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5114
      total_pages: 514
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5114.txt
    statistics:
      ocr_word_median_confidence_index: 0.9005838
      ocr_word_mean_confidence_index: 0.8636745204468247
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
